/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Genre = IDL.Variant({
  'thriller' : IDL.Null,
  'love' : IDL.Null,
  'historical' : IDL.Null,
  'scienceFiction' : IDL.Null,
  'horror' : IDL.Null,
  'romance' : IDL.Null,
  'fantasy' : IDL.Null,
});
export const Time = IDL.Int;
export const Story = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'creationDate' : Time,
  'genre' : Genre,
  'isAIGenerated' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Genre], [], []),
  'filterStoriesByGenre' : IDL.Func([Genre], [IDL.Vec(Story)], ['query']),
  'getStory' : IDL.Func([IDL.Text], [Story], ['query']),
  'listAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Genre = IDL.Variant({
    'thriller' : IDL.Null,
    'love' : IDL.Null,
    'historical' : IDL.Null,
    'scienceFiction' : IDL.Null,
    'horror' : IDL.Null,
    'romance' : IDL.Null,
    'fantasy' : IDL.Null,
  });
  const Time = IDL.Int;
  const Story = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'creationDate' : Time,
    'genre' : Genre,
    'isAIGenerated' : IDL.Bool,
  });
  
  return IDL.Service({
    'createStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Genre], [], []),
    'filterStoriesByGenre' : IDL.Func([Genre], [IDL.Vec(Story)], ['query']),
    'getStory' : IDL.Func([IDL.Text], [Story], ['query']),
    'listAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };