/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Genre = { 'thriller' : null } |
  { 'love' : null } |
  { 'historical' : null } |
  { 'scienceFiction' : null } |
  { 'horror' : null } |
  { 'romance' : null } |
  { 'fantasy' : null };
export interface Story {
  'title' : string,
  'content' : string,
  'author' : string,
  'creationDate' : Time,
  'genre' : Genre,
  'isAIGenerated' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'createStory' : ActorMethod<[string, string, string, Genre], undefined>,
  'filterStoriesByGenre' : ActorMethod<[Genre], Array<Story>>,
  'getStory' : ActorMethod<[string], Story>,
  'listAllStories' : ActorMethod<[], Array<Story>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];