/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Story {
    title: string;
    content: string;
    author: string;
    creationDate: Time;
    genre: Genre;
    isAIGenerated: boolean;
}
export enum Genre {
    thriller = "thriller",
    love = "love",
    historical = "historical",
    scienceFiction = "scienceFiction",
    horror = "horror",
    romance = "romance",
    fantasy = "fantasy"
}
export interface backendInterface {
    createStory(title: string, content: string, author: string, genre: Genre): Promise<void>;
    filterStoriesByGenre(genre: Genre): Promise<Array<Story>>;
    getStory(title: string): Promise<Story>;
    listAllStories(): Promise<Array<Story>>;
}
import type { Genre as _Genre, Story as _Story, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createStory(arg0: string, arg1: string, arg2: string, arg3: Genre): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1, arg2, to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1, arg2, to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async filterStoriesByGenre(arg0: Genre): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterStoriesByGenre(to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterStoriesByGenre(to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStory(arg0: string): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.getStory(arg0);
                return from_candid_Story_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStory(arg0);
            return from_candid_Story_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStories();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStories();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Genre_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    author: string;
    creationDate: _Time;
    genre: _Genre;
    isAIGenerated: boolean;
}): {
    title: string;
    content: string;
    author: string;
    creationDate: Time;
    genre: Genre;
    isAIGenerated: boolean;
} {
    return {
        title: value.title,
        content: value.content,
        author: value.author,
        creationDate: value.creationDate,
        genre: from_candid_Genre_n6(_uploadFile, _downloadFile, value.genre),
        isAIGenerated: value.isAIGenerated
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thriller: null;
} | {
    love: null;
} | {
    historical: null;
} | {
    scienceFiction: null;
} | {
    horror: null;
} | {
    romance: null;
} | {
    fantasy: null;
}): Genre {
    return "thriller" in value ? Genre.thriller : "love" in value ? Genre.love : "historical" in value ? Genre.historical : "scienceFiction" in value ? Genre.scienceFiction : "horror" in value ? Genre.horror : "romance" in value ? Genre.romance : "fantasy" in value ? Genre.fantasy : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Genre_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    thriller: null;
} | {
    love: null;
} | {
    historical: null;
} | {
    scienceFiction: null;
} | {
    horror: null;
} | {
    romance: null;
} | {
    fantasy: null;
} {
    return value == Genre.thriller ? {
        thriller: null
    } : value == Genre.love ? {
        love: null
    } : value == Genre.historical ? {
        historical: null
    } : value == Genre.scienceFiction ? {
        scienceFiction: null
    } : value == Genre.horror ? {
        horror: null
    } : value == Genre.romance ? {
        romance: null
    } : value == Genre.fantasy ? {
        fantasy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
